version: "3"

services:

#
# Webserver
#           
  web_identity_provider:
    image: harpya/web_identity_provider:0.0.17
    env_file: 
      - ip.env     
    ports:
      - "${IP_WEB_EXPOSED_PORT}:80"
    #   - "${WEBSERVER_SSL_EXPOSED_PORT}:443"
    networks:
      demo_1_net:


#
# Application
#         
  app_identity_provider:
    image: harpya/app_identity_provider:0.0.18
    env_file: 
      - ip.env    
    working_dir: ${IP_PHP_APP_DIR}
    depends_on:
      - web_identity_provider
      - db_identity_provider
    networks:
      demo_1_net:

#
# Transactional DB
#
  db_identity_provider:
    build:
      context: .docker
      dockerfile: db-timescale/Dockerfile
    env_file: 
      - ip.env 
    volumes:
      - vol_db_identity_provider:/var/lib/postgresql/data
    networks:
      demo_1_net:
    
#
# Web IDE to access db_transactional
#
  adminer:
    image: adminer
    restart: always
    ports:
      - 42345:8080
    networks:
      demo_1_net:
  




#
# Webserver
#           
  web:
    build:
      context: .docker/web
      args:
        - WEB_USER=www-data
        - WEB_GROUP=www-data
        - APACHE_ROOT_DIR=/usr/local/apache2
    ports:
      - "${APP_WEB_EXPOSED_PORT}:80"
    #   - "${WEBSERVER_SSL_EXPOSED_PORT}:443"
    env_file: 
      - app.env 
    volumes:
      - ./app:/var/www/html
    networks:
      demo_1_net:


  #
  # Application
  #         
  app:
    build:
      context: .docker
      dockerfile: php-debug/Dockerfile
      args:
        - WEB_USER=www-data
        - WEB_GROUP=www-data
        - APACHE_ROOT_DIR=/usr/local/apache2
        - PHP_ROOT_DIR=/usr/local/etc
        - XDEBUG_PORT=19001
    working_dir: /var/www/html
    depends_on:
      - web
    volumes:
      - ./app:/var/www/html
    env_file: 
      - app.env 
    networks:
      demo_1_net:




#
# Transactional DB
#
  db:
    build:
      context: .docker
      dockerfile: db-timescale/Dockerfile
    env_file: 
      - app.env 
    volumes:
      - vol_db_app:/var/lib/postgresql/data
    networks:
      demo_1_net:
  


  mailer:
    image: schickling/mailcatcher
    ports:
      - "18888:1080"
    networks:
      demo_1_net:
  


volumes:
  vol_db_app:
  vol_db_identity_provider:  

networks:
  demo_1_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_SUBNET}