<html>
<head>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <!-- <script src="https://cdn.jsdelivr.net/jquery.validation/1.15.1/jquery.validate.min.js"></script> -->

    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

</head>
<body>

<div class="container">


<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <?php if (\Harpya\demo\App::getInstance()->isAuthenticated()) {
    ?>
      <li class="nav-item">
        <a class="nav-link" href="/profile">Profile</a>
      </li>
     
<?php
} else {
        ?>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Profile</a>
      </li>
      <?php
    } ?>
    </ul>

    <?php if (\Harpya\demo\App::getInstance()->isAuthenticated()) {
        ?>
    <div>
        <a href="/logout" class="btn btn-outline-success my-2 my-sm-0">Logout</a>
    </div>

    <?php
    } else {
        ?>

    <form class="form-inline my-2 my-lg-0" method="post" action="/login">
      <input class="form-control mr-sm-2" type="email" name="email" placeholder="email" aria-label="email">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Login</button>
    </form>
    <?php
    } ?>
  </div>
</nav>
