
    <?php include_once __DIR__ . '/header.phtml'; ?>

<div class="row">

    <div class="col-md-5 mx-auto">
        <h1>Profile</h1>
        
        <table class="table">
            <tr>
                <th>Email</th>
                <td><?= $email ?></td>
            </tr>
            <tr>
                <th>IP</th>
                <td><?= $ip ?></td>
            </tr>
            <tr>
                <th>Login at</th>
                <td><?= $loginAt ?></td>
            </tr>
        </table>

    </div>
</div>

</div>

<?php include_once __DIR__ . '/footer.phtml'; ?>
