
    <?php include_once __DIR__ . '/header.phtml'; ?>

        <div class="row">

            <div class="col-md-5 mx-auto">
                <h1>Welcome</h1>
                Your IP is <?=$_SERVER['REMOTE_ADDR'] ?>
                <p>
                <?=$msg ?>
                </p>
            </div>
        </div>

        <!-- <div class="row">

            <div class="col-md-5 mx-auto">

                <form method="post" action="/login">
                    <input type="email" name="email" class="form-control">
                    <br/>

                    <input type="submit" class="btn btn-small" value="Login"/>

                </form>

            </div>
        </div> -->
</div>

<?php include_once __DIR__ . '/footer.phtml'; ?>
